### ISSUE TITLE
Port to Python3

### ISSUE THREAD

**Issue by manuelbua** [manuelbua/gitver#26]

**Comment by blackandred** [comment]
Hi, is there any progress on it? :wink:

**Comment by magarciasopo** [comment]
Hi there, 

I am facing an error when I try to install with pip3: 

`  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/42/mrkqsblj5pb0mjgg6j3kqfwh0000gp/T/pip-install-eyej37yx/gitver_cce89a366ea841ebbcc00f59e3baa6c1/setup.py", line 23
          print "Warning: the \"pypandoc\" package and/or the pandoc " \
                ^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Warning: the \"pypandoc\" package and/or the pandoc " \)?
      [end of output]`

Could it be there still not support for python3?

Thanks!

**Comment by manuelbua** [comment]
Hi, yes unfortunately i've never been able to put some time into this and port it to python3.
